;;; multi-compile-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from multi-compile.el

(autoload 'multi-compile-locate-file-dir "multi-compile" "\
Look up the directory hierarchy from current file for a directory containing file NAME.

(fn NAME)")
(autoload 'multi-compile-run "multi-compile" "\
Choice target and start compile." t)
(register-definition-prefixes "multi-compile" '("multi-compile-"))

;;; End of scraped data

(provide 'multi-compile-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; multi-compile-autoloads.el ends here
